### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by awseward** [awseward/spiderman-points#1]
### TODO
- [x] OAuth shenanigans
- [x] ~App published in marketplace (requires OAuth shenanigans)~ Holding off until there's more of a reson to do this
- [x] SSL / https
- [x] Add to Slack button / landing page on `GET /`
- [ ] Gifs?
- [ ] Reactions
- [x] Leaderboard (for points given, not received)
- [x] Recent points (just mine? all?)
